---
- name: prepare container for test
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Create container centos7
      docker_container:
        name: centos7
        image: centos:7
        recreate: yes
        command: tail -f /dev/null
        state: started

    - name: add centos7 host
      add_host: name=centos7 groups=containers
 
    - name: Create container centos6
      docker_container:
        name: centos6
        image: centos:6
        recreate: yes
        command: tail -f /dev/null
        state: started

    - name: add centos6 host
      add_host: name=centos6 groups=containers

- name: test role
  hosts: containers
  connection: docker
  roles:
    - "{{ playbook_dir }}"

- name: tear down
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Destroy containers
      docker_container:
        name: '{{ item }}'
        state: absent
      with_items:
        - centos6
        - centos7
