---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint molecule/default/converge.yml
  ansible-lint molecule/default/converge.yml
  flake8 molecule/default/
platforms:
  - name: centos7
    image: centos:7
    pre_build_image: true
  - name: centos8
    image: centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
